// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ITB_ResizeMessageWindow","status":true,"description":"v.1.0 メッセージウインドウのサイズ(幅・行数)を変更します。","parameters":{"mwwdr":"60","mwrow":"3"}},
{"name":"Keke_TitleSkip","status":true,"description":"タイトル画面を飛ばし高速プレイ","parameters":{"タイトルスキップ":"true","スキップ先":"ニューゲーム","自動ロード":"","初回のみスキップ":"","ページキーでタイトル":"true","ロード画面":"","タイトルに戻さない":"false","ロード画面でニューゲーム":"true","ロード画面にタイトル画像":"true","ロード不透明度":"128","フェード時間":"","タイトル":"8","ロード":"6","ニューゲーム後":"12","ロード後":"8","ゲーム終了":"0"}},
{"name":"ITB_PictureParallax","status":true,"description":"v.1.0 任意のピクチャを画面スクロールの影響を受けるようにします。","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"ピクチャをクリック可能にします。","parameters":{}},
{"name":"InputDialog_Custom","status":true,"description":"ゲーム内に文字入力ウィンドウを配置するプラグイン\r\nオリジナルの入力ウィンドウを作成出来ます。","parameters":{"fontFileName":"","formWidth":"400px","formHeight":"auto","formBackgroundColor":"rgba(0, 0, 0, 0.5)","formBorder":"3px solid #fff","formBorderRadius":"5px","formPadding":"30px","labelTextColor":"#FFFFFF","labelTextFontSize":"18px","labelTextMarginBottom":"10px","inputWidth":"100%","inputHeight":"40px","inputFontSize":"18px","inputColor":"#FFFFFF","inputBackgroundColor":"rgba(0, 0, 0, 0.5)","inputBorder":"1px solid #fff","inputBorderRadius":"5px","inputPadding":"5px","buttonContainerWidth":"100%","buttonContainerMargin":"15px 0 0 0","okButtonWidth":"120px","okButtonHeight":"40px","okButtonFontSize":"18px","okButtonColor":"#FFFFFF","okButtonBackgroundColor":"rgba(0, 0, 0, 0.5)","okButtonBorder":"1px solid #fff","okButtonBorderRadius":"5px","okButtonPadding":"5px 10px","cancelButtonWidth":"0","cancelButtonHeight":"0","cancelButtonFontSize":"0","cancelButtonColor":"#FFFFFF","cancelButtonBackgroundColor":"rgba(0, 0, 0, 0.5)","cancelButtonBorder":"0","cancelButtonBorderRadius":"0","cancelButtonPadding":"0","cancelButtonMarginLeft":"0"}},
{"name":"MyApiPlugin","status":true,"description":"XREA PHP API連携プラグイン","parameters":{"baseUrl":"http://www.icedtomatobazooka.shop/api.php"}},
{"name":"TextPicture","status":true,"description":"テキストをピクチャとして表示します。","parameters":{}}
];
