// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ITB_ResizeMessageWindow","status":true,"description":"v.1.0 メッセージウインドウのサイズ(幅・行数)を変更します。","parameters":{"mwwdr":"60","mwrow":"3"}},
{"name":"Keke_TitleSkip","status":true,"description":"タイトル画面を飛ばし高速プレイ","parameters":{"タイトルスキップ":"true","スキップ先":"ニューゲーム","自動ロード":"","初回のみスキップ":"","ページキーでタイトル":"true","ロード画面":"","タイトルに戻さない":"false","ロード画面でニューゲーム":"true","ロード画面にタイトル画像":"true","ロード不透明度":"128","フェード時間":"","タイトル":"8","ロード":"6","ニューゲーム後":"12","ロード後":"8","ゲーム終了":"0"}},
{"name":"ITB_PictureParallax","status":true,"description":"v.1.0 任意のピクチャを画面スクロールの影響を受けるようにします。","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"ピクチャをクリック可能にします。","parameters":{}}
];
